// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/complete-guide" | "/docs/security" | "/flywheel" | "/glossary" | "/learn" | "/learn/[slug]" | "/learn/commands" | "/learn/glossary" | "/learn/tools/[tool]" | "/tldr" | "/tools" | "/troubleshooting" | "/wizard/accounts" | "/wizard/create-vps" | "/wizard/generate-ssh-key" | "/wizard/install-terminal" | "/wizard/launch-onboarding" | "/wizard/os-selection" | "/wizard/preflight-check" | "/wizard/reconnect-ubuntu" | "/wizard/rent-vps" | "/wizard/run-installer" | "/wizard/ssh-connect" | "/wizard/status-check" | "/wizard/verify-key-connection" | "/wizard/windows-terminal-setup" | "/workflow"
type AppRouteHandlerRoutes = "/api/track" | "/install"
type PageRoutes = never
type LayoutRoutes = "/" | "/complete-guide" | "/flywheel" | "/learn" | "/tldr" | "/wizard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/track": {}
  "/complete-guide": {}
  "/docs/security": {}
  "/flywheel": {}
  "/glossary": {}
  "/install": {}
  "/learn": {}
  "/learn/[slug]": { "slug": string; }
  "/learn/commands": {}
  "/learn/glossary": {}
  "/learn/tools/[tool]": { "tool": string; }
  "/tldr": {}
  "/tools": {}
  "/troubleshooting": {}
  "/wizard": {}
  "/wizard/accounts": {}
  "/wizard/create-vps": {}
  "/wizard/generate-ssh-key": {}
  "/wizard/install-terminal": {}
  "/wizard/launch-onboarding": {}
  "/wizard/os-selection": {}
  "/wizard/preflight-check": {}
  "/wizard/reconnect-ubuntu": {}
  "/wizard/rent-vps": {}
  "/wizard/run-installer": {}
  "/wizard/ssh-connect": {}
  "/wizard/status-check": {}
  "/wizard/verify-key-connection": {}
  "/wizard/windows-terminal-setup": {}
  "/workflow": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/complete-guide": never
  "/flywheel": never
  "/learn": never
  "/tldr": never
  "/wizard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
