// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/complete-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complete-guide">> = Specific
  const handler = {} as typeof import("../../../app/complete-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/security">> = Specific
  const handler = {} as typeof import("../../../app/docs/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/flywheel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flywheel">> = Specific
  const handler = {} as typeof import("../../../app/flywheel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/glossary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/glossary">> = Specific
  const handler = {} as typeof import("../../../app/glossary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/learn/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/commands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/commands">> = Specific
  const handler = {} as typeof import("../../../app/learn/commands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/glossary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/glossary">> = Specific
  const handler = {} as typeof import("../../../app/learn/glossary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../../app/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/tools/[tool]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/tools/[tool]">> = Specific
  const handler = {} as typeof import("../../../app/learn/tools/[tool]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tldr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tldr">> = Specific
  const handler = {} as typeof import("../../../app/tldr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../../app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/troubleshooting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/troubleshooting">> = Specific
  const handler = {} as typeof import("../../../app/troubleshooting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/accounts">> = Specific
  const handler = {} as typeof import("../../../app/wizard/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/create-vps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/create-vps">> = Specific
  const handler = {} as typeof import("../../../app/wizard/create-vps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/generate-ssh-key/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/generate-ssh-key">> = Specific
  const handler = {} as typeof import("../../../app/wizard/generate-ssh-key/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/install-terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/install-terminal">> = Specific
  const handler = {} as typeof import("../../../app/wizard/install-terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/launch-onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/launch-onboarding">> = Specific
  const handler = {} as typeof import("../../../app/wizard/launch-onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/os-selection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/os-selection">> = Specific
  const handler = {} as typeof import("../../../app/wizard/os-selection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/preflight-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/preflight-check">> = Specific
  const handler = {} as typeof import("../../../app/wizard/preflight-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/reconnect-ubuntu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/reconnect-ubuntu">> = Specific
  const handler = {} as typeof import("../../../app/wizard/reconnect-ubuntu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/rent-vps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/rent-vps">> = Specific
  const handler = {} as typeof import("../../../app/wizard/rent-vps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/run-installer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/run-installer">> = Specific
  const handler = {} as typeof import("../../../app/wizard/run-installer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/ssh-connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/ssh-connect">> = Specific
  const handler = {} as typeof import("../../../app/wizard/ssh-connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/status-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/status-check">> = Specific
  const handler = {} as typeof import("../../../app/wizard/status-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/verify-key-connection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/verify-key-connection">> = Specific
  const handler = {} as typeof import("../../../app/wizard/verify-key-connection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/windows-terminal-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/windows-terminal-setup">> = Specific
  const handler = {} as typeof import("../../../app/wizard/windows-terminal-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/workflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow">> = Specific
  const handler = {} as typeof import("../../../app/workflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../../app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/install">> = Specific
  const handler = {} as typeof import("../../../app/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/complete-guide/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/complete-guide">> = Specific
  const handler = {} as typeof import("../../../app/complete-guide/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/flywheel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/flywheel">> = Specific
  const handler = {} as typeof import("../../../app/flywheel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learn/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../../app/learn/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tldr/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tldr">> = Specific
  const handler = {} as typeof import("../../../app/tldr/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wizard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/wizard">> = Specific
  const handler = {} as typeof import("../../../app/wizard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
